training:
    batch_size: 32
    n_timesteps: 1000
    continuous: true
    n_steps: 500000
    resolution: 32
    step_size: 0.1
    lr_gen: 0.0001
    lr_disc: 0.0001
    mse_coeff: 0.001
    lpips_coeff: 10
    boundary_coeff: 0.1
    ema_rate: 0.9999
    gen_log_freq: 1000
    disc_log_freq: 1000
    ema_update_freq: 100
    image_log_freq: 1000
    save_ckpt_freq: 5000
    discr_update_freq: 20
    beta_max: 19.9
    beta_min: 0.1
unet:
    in_channels: 3
    model_channels: 128
    out_channels: 3
    num_res_blocks: 2
    attention_resolutions: [16, 8]
    dropout: 0
    channel_mult: [1, 1, 2, 2, 4, 4]
    conv_resample: true
    dims: 2
    num_classes: null
    use_checkpoint: false
    num_heads: 1
    num_heads_upsample: -1
    use_scale_shift_norm: false
    return_hidden: true
discriminator:
    n_classes: 1
    in_features: 64 
    img_features: 3
    lowest_resolution: 4 
    time_features: 64