training:
    solver: heun
    batch_size: 96
    n_timesteps: 1000
    sampling_countinious: true 
    n_steps: 500000
    resolution: 32
    step_size: 0.04
    lr_gen: 0.0005
    boundary_coeff: 200
    gen_log_freq: 1000
    image_log_freq: 1000
    save_ckpt_freq: 5000
    beta_max: 20.0
    beta_min: 0.1
unet:
    in_channels: 3
    model_channels: 128
    out_channels: 3
    num_res_blocks: 2
    attention_resolutions: [16, 8]
    dropout: 0
    channel_mult: [1, 1, 2, 2, 4, 4]
    conv_resample: true
    dims: 2
    num_classes: null
    use_checkpoint: false
    num_heads: 1
    num_heads_upsample: -1
    use_scale_shift_norm: false
    return_hidden: true